### ISSUE TITLE
Encryption via Session Keys

### ISSUE THREAD

**Issue by JohnDoneth** [BonsaiDen/cobalt-rs#7]
I propose per packet encryption via session keys per packet when connecting to the server for the first time. The session key (a symmetric key) will be generated for both the client and server using a public key (an asymmetric key) using something like the Diffie–Hellman key exchange protocol.

After the session key is established per connection; we use the session key to encrypt outgoing client traffic and decrypt it at the server, and vice-versa because the client and server now share a secret key.

There are already a few crypto libraries for Rust such as [Ring](https://github.com/briansmith/ring), and bindings to [OpenSSL](https://github.com/sfackler/rust-openssl) that could be used.

Of course, this is just an idea, and there might be a better way to go about encrypting network traffic.

**Comment by inlife** [comment]
Or possibly a nice way is to add a pre-send callback for inserting your own handler for encryption.
Keeping deps nice and minimal :D
